package com.example.physicistscard.android.ui.screens.storeScreens.basicItems

// val physicistsProducts = listOf(
//     Product(id = "1", name = "艾萨克·牛顿", category = "物理学家", description = "经典物理学的奠基人之一，提出了万有引力定律。", price = "¥6"),
//     Product(id = "2", name = "阿尔伯特·爱因斯坦", category = "物理学家", description = "相对论的创立者，对现代物理学产生了深远影响。", price = "¥6"),
//     Product(id = "3", name = "詹姆斯·克拉克·麦克斯韦", category = "物理学家", description = "电磁理论的奠基人，提出了麦克斯韦方程组。", price = "¥6"),
//     Product(id = "4", name = "史蒂芬·霍金", category = "物理学家", description = "黑洞辐射理论的提出者，宇宙学和量子引力理论的重要贡献者。", price = "¥6"),
//     Product(id = "5", name = "罗伯特·奥本海默", category = "物理学家", description = "曼哈顿计划的科学领导，被称为原子弹的父亲。", price = "¥6"),
//     Product(id = "6", name = "杨振宁", category = "物理学家", description = "杨-米尔斯理论的提出者，对量子场论做出了重大贡献。", price = "¥6"),
//     Product(id = "7", name = "阿基米德", category = "物理学家", description = "古希腊的物理学家和数学家，对力学和浮力理论有重要发现。", price = "¥6"),
//     Product(id = "8", name = "相对论", category = "理论学说", description = "描述宏观物体运动和引力现象的基本理论框架。", price = "¥6"),
//     Product(id = "9", name = "量子力学", category = "理论学说", description = "描述微观粒子物理行为的基本理论。", price = "¥6"),
//     Product(id = "10",name = "热力学第二定律", category = "理论学说", description = "定义了物理系统熵的概念，预言了熵增原理。", price = "¥6"),
//     Product(id = "11",name = "电磁理论", category = "理论学说", description = "描述电磁场与电荷之间相互作用的理论。", price = "¥6"),
//     Product(id = "12",name = "弦理论", category = "理论学说", description = "试图统一所有基本粒子和力的理论框架。", price = "¥6"),
//     Product(id = "13",name = "宇宙学原理", category = "理论学说", description = "宇宙是均匀且各向同性的基本假设。", price = "¥6"),
//     Product(id = "14",name = "双缝实验", category = "经典实验", description = "展示了光和物质的波粒二象性的著名实验。", price = "¥6"),
//     Product(id = "15",name = "苹果落地", category = "经典实验", description = "牛顿观察苹果落地启发万有引力定律的故事。", price = "¥6"),
//     Product(id = "16",name = "迈克耳孙-莫雷实验", category = "经典实验", description = "旨在检测地球相对于“以太”运动的实验，结果支持了相对论的基本假设。", price = "¥6"),
//     Product(id = "17",name = "光电效应实验", category = "经典实验", description = "证明了光的粒子性，为量子物理学的发展奠定了基础。", price = "¥6"),
//     Product(id = "18",name = "黄金分割实验", category = "经典实验", description = "探索自然和艺术中黄金分割比例的应用。", price = "¥6"),
//     Product(id = "19",name = "磁场中的铜环实验", category = "经典实验", description = "展示了电磁感应现象的实验。", price = "¥6"),
//     Product(id = "20",name = "黑洞", category = "物理现象", description = "引力强大到连光都无法逃脱的天体。", price = "¥6"),
//     Product(id = "21",name = "量子纠缠", category = "物理现象", description = "量子态间的一种强相关性，违反了经典物理学的局域性原理。", price = "¥6"),
//     Product(id = "22",name = "超导现象", category = "物理现象", description = "材料在低温下电阻消失的现象。", price = "¥6"),
//     Product(id = "23",name = "光的折射", category = "物理现象", description = "光线从一种介质进入另一种介质时速度改变引起的方向改变。", price = "¥6"),
//     Product(id = "24",name = "引力波", category = "物理现象", description = "由于质量加速运动产生的时空涟漪。", price = "¥6"),
//     Product(id = "25",name = "霍金辐射", category = "物理现象", description = "黑洞表面由于量子效应而发出的辐射。", price = "¥6"),
//     Product(id = "26",name = "量子计算机", category = "尖端技术", description = 途广泛。", price = "¥6"),
////     Product(id = "30",name = "石墨烯", category = "尖端技术", description = "一种由单层碳原子组成的二维材料，具有许多独特的物理性质。", price = "¥6"),
////     Product(id = "31",name = "暗物质探测", category = "尖端技术", description = "旨在探"利用量子位进行计算的新型计算机。", price = "¥6"),
//     Product(id = "27",name = "引力波探测器", category = "尖端技术", description = "用于探测宇宙中引力波事件的高精度仪器。", price = "¥6"),
//     Product(id = "28",name = "光纤通讯", category = "尖端技术", description = "使用光信号进行通讯的技术，具有高速度和远距离传输的特点。", price = "¥6"),
//     Product(id = "29",name = "碳纳米管", category = "尖端技术", description = "具有特殊性质的纳米级碳管，用测和研究宇宙中未知的暗物质组成的技术。", price = "¥6"),
//     Product(id = "32", name = "尼尔斯·玻尔", category = "物理学家", description = "原子结构和量子力学的先驱。", price = "¥6"),
//     Product(id = "33", name = "迈克尔·法拉第", category = "物理学家", description = "电磁感应、电磁场理论的奠基人。", price = "¥6"),
//     Product(id = "34", name = "恩里科·费米", category = "物理学家", description = "原子弹项目的关键人物，量子理论的贡献者。", price = "¥6"),
//     Product(id = "35", name = "理查德·费曼", category = "物理学家", description = "量子电动力学的重要贡献者，诺贝尔奖得主。", price = "¥6"),
//     Product(id = "36", name = "薛定谔", category = "物理学家", description = "薛定谔方程的提出者，量子力学的奠基人之一。", price = "¥6"),
//     Product(id = "37", name = "海森堡", category = "物理学家", description = "不确定性原理的提出者，量子力学的重要人物。", price = "¥6"),
//     Product(id = "38", name = "勒内·笛卡尔", category = "物理学家", description = "分析几何之父，哲学家和科学家。", price = "¥6"),
//     // Product(id = "39", name = "詹姆斯·瓦特", category = "物理学家", description = "蒸汽机的改良者，工业革命的关键人物。", price = "¥6"),
//     // Product(id = "51", name = "路德维希·玻尔兹曼", category = "物理学家", description = "统计力学和热力学贡献者。", price = "¥6"),
//     // Product(id = "52", name = "马克斯·普朗克", category = "物理学家", description = "量子理论的创始人之一。", price = "¥6"),
//     // Product(id = "53", name = "维尔纳·海森堡", category = "物理学家", description = "量子力学的奠基人之一，不确定性原理的提出者。", price = "¥6"),
//     // Product(id = "54", name = "埃尔温·薛定谔", category = "物理学家", description = "薛定谔方程的提出者，量子力学的重要人物。", price = "¥6"),
//     // Product(id = "55", name = "保罗·狄拉克", category = "物理学家", description = "量子力学和量子场论的重要贡献者。", price = "¥6"),
//     // Product(id = "56", name = "狄拉克海", category = "理论学说", description = "描述了反粒子存在的理论海。", price = "¥6"),
//     Product(id = "57", name = "霍金辐射", category = "物理现象", description = "黑洞表面发射的辐射，由斯蒂芬·霍金提出。", price = "¥6"),
//     Product(id = "58", name = "宇宙微波背景辐射", category = "物理现象", description = "支持宇宙大爆炸理论的关键证据之一。", price = "¥6"),
//     Product(id = "59", name = "沃纳·海森堡", category = "物理学家", description = "量子力学的奠基人之一，著名的不确定性原理的提出者。", price = "¥6"),
//     Product(id = "60", name = "保罗·狄拉克", category = "物理学家", description = "量子力学和量子电动力学的重要贡献者，预言了反物质的存在。", price = "¥6")
// )